// Blog / guides. Each post: blocks are rendered by components/PostBody.js.
// Inline syntax inside text: **bold** and [link text](url). Keep every claim sourced.

export const posts = [
  {
    slug: "how-to-get-more-google-reviews",
    title: "How to get more Google reviews (without breaking Google's rules)",
    seoTitle: "How to Get More Google Reviews Without Breaking the Rules",
    description:
      "A practical guide for Vancouver businesses: how to ask for Google reviews, what Google and Canadian law prohibit, and how to reply so reviews help you rank.",
    date: "2026-10-08",
    category: "Google Business Profile",
    service: "google-business-profile",
    readMinutes: 6,
    excerpt:
      "Reviews help you rank and help customers choose you. Here's how to get more of them the right way, and the shortcuts that can get your profile restricted.",
    blocks: [
      { type: "p", text: "For most local businesses, Google reviews do two jobs at once. They help customers decide between you and the place down the street, and they're one of the signals Google uses to decide who shows up in the map pack in the first place." },
      { type: "p", text: "Google says local results are based mainly on relevance, distance and prominence, and that \"more reviews and positive ratings can help your business's local ranking\" ([Google](https://support.google.com/business/answer/7091)). You can't change your distance from a searcher. You can change how many recent, genuine reviews you have." },
      { type: "h2", text: "Why the number and freshness of reviews matter" },
      { type: "p", text: "Customers read recent reviews to judge what a business is like now, not three years ago. A profile with a steady stream of new reviews, and thoughtful replies to them, looks active and trustworthy. A profile whose last review is from last spring looks like it might be closed." },
      { type: "p", text: "Volume matters too. A 4.8 from 12 reviews is less convincing than a 4.6 from 240. The goal isn't a perfect score. It's a steady flow of honest feedback from real customers." },
      { type: "h2", text: "What Google doesn't allow" },
      { type: "p", text: "Before you start asking, know where the lines are. Google's contributed content policy prohibits ([Google](https://support.google.com/contributionpolicy/answer/7400114)):" },
      { type: "ul", items: [
        "**Paying for reviews** or offering incentives such as discounts, free items or services in exchange for a review.",
        "**Selectively asking happy customers only** (often called review gating), or discouraging negative reviews.",
        "**Pressuring customers to review while they're still on the premises.**",
        "**Asking staff to collect reviews that include specific content**, such as particular keywords or phrases.",
        "**Reviews from people with a conflict of interest**, including current or former employees and contractors.",
      ] },
      { type: "p", text: "Google's own help page for businesses is blunt about incentives: offering free or discounted goods or services in exchange for reviews is \"strictly prohibited\" ([Google](https://support.google.com/business/answer/3474122)). Breaking these rules can get reviews removed and, in more serious cases, restrictions placed on your profile." },
      { type: "h2", text: "The Canadian side: fake reviews are a legal risk too" },
      { type: "p", text: "In Canada, the Competition Bureau treats fake reviews as misleading to consumers. It warns that companies posting fake reviews to boost their own ratings or hurt competitors \"are misleading consumers and harming businesses that play by the rules\" ([Competition Bureau](https://www.canada.ca/en/competition-bureau/news/2017/03/fake_online_reviewstoogoodtobetrue.html))." },
      { type: "p", text: "This isn't theoretical. In 2015, Bell Canada agreed to pay a $1.25 million penalty after employees were encouraged to post positive reviews of its apps without disclosing who they worked for ([iPhone in Canada](https://www.iphoneincanada.ca/2015/10/14/bell-fined-fake-reviews/))." },
      { type: "h2", text: "Seven ways to get more genuine reviews" },
      { type: "ol", items: [
        "**Make leaving a review effortless.** Get your review link or QR code from your Google Business Profile, as Google recommends ([Google](https://support.google.com/business/answer/3474122)). Every extra tap loses people.",
        "**Ask everyone, at the right moment.** Ask every customer, not just the ones who seem happy. Time it to when the value is fresh: after a meal, when a project is handed over, after a treatment or at the end of a program.",
        "**Put the QR code where customers already pause.** Table tents, the receipt, the counter, the checkout screen, the packaging. Let people scan it on their own time rather than pressing them on the spot.",
        "**Follow up by text or email.** A short message a few hours or a day later, with the direct link, consistently brings in more reviews than an in-person ask alone.",
        "**Train your team on the ask, not the wording.** Staff can say \"we'd really appreciate a Google review\", but they shouldn't tell customers what to write.",
        "**Reply to reviews, good and bad.** Customers notice when a business responds, and replies show Google the profile is actively managed.",
        "**Keep it steady.** Ten reviews in a week followed by nothing for months looks less natural, and helps you less, than two or three a week every week.",
      ] },
      { type: "h2", text: "How to reply to reviews" },
      { type: "p", text: "Google recommends that replies be polite, short and relevant, that you skip generic thank-yous, and that you don't use replies to advertise deals ([Google](https://support.google.com/business/answer/3474122)). In practice:" },
      { type: "ul", items: [
        "**Positive reviews:** thank them by name, mention something specific they said, and invite them back.",
        "**Negative reviews:** stay calm, acknowledge what went wrong, explain what you're doing about it and offer a way to continue the conversation privately. Never share a customer's private details or argue in public.",
        "**Reviews that break Google's rules:** flag them for removal through your Business Profile instead of arguing with the reviewer.",
      ] },
      { type: "tip", text: "Regulated professions such as physicians, nurses and dentists often have advertising rules about how patient reviews and testimonials can be used. You can usually still reply to reviews, but check your college's standards before featuring reviews in your marketing." },
      { type: "h2", text: "A simple review system you can set up this week" },
      { type: "ol", items: [
        "Copy your review link from your Google Business Profile and create a QR code.",
        "Add the QR code to your receipts, counter, table tents or invoices.",
        "Write a short follow-up text or email and send it to every customer within a day.",
        "Pick one person to reply to every new review within 48 hours.",
        "Check your review count once a month, and adjust where and when you ask.",
      ] },
      { type: "p", text: "If you'd rather have it done for you, we set up review systems as part of our [Google Business Profile management](/services/google-business-profile), including QR codes, follow-up messages and replies written in your brand voice." },
    ],
    faqs: [
      { q: "Can I offer a discount for a Google review?", a: "No. Google prohibits offering discounts, free items or any other incentive in exchange for reviews, and incentivized reviews can be removed." },
      { q: "Is it OK to only ask happy customers for reviews?", a: "No. Google's policy prohibits selectively asking for positive reviews. Ask every customer and let them share their honest experience." },
      { q: "Can my employees or family leave reviews?", a: "They shouldn't. Google's policy treats current and former employees and other conflicts of interest as fake engagement." },
      { q: "How many Google reviews do I need?", a: "There's no magic number. What matters most is having more recent, genuine reviews than the businesses you compete with in the map pack, and a steady flow of new ones." },
    ],
    sources: [
      { label: "Google: Tips to improve your local ranking", url: "https://support.google.com/business/answer/7091" },
      { label: "Google: Maps user contributed content policy (fake engagement)", url: "https://support.google.com/contributionpolicy/answer/7400114" },
      { label: "Google: Read & reply to reviews", url: "https://support.google.com/business/answer/3474122" },
      { label: "Competition Bureau Canada: Fake online reviews", url: "https://www.canada.ca/en/competition-bureau/news/2017/03/fake_online_reviewstoogoodtobetrue.html" },
      { label: "iPhone in Canada: Bell fined $1.25 million over fake app reviews", url: "https://www.iphoneincanada.ca/2015/10/14/bell-fined-fake-reviews/" },
    ],
  },
  {
    slug: "how-to-rank-higher-on-uber-eats-doordash-skipthedishes",
    title: "How to rank higher on Uber Eats, DoorDash and SkipTheDishes",
    seoTitle: "How to Rank Higher on Uber Eats, DoorDash & SkipTheDishes",
    description:
      "What the delivery apps actually reward, from ratings and photos to cancellations and menu markup, and a checklist BC restaurants can use to get more orders.",
    date: "2026-10-08",
    category: "Delivery platforms",
    service: "delivery-platforms",
    readMinutes: 5,
    excerpt:
      "Delivery apps are search engines with their own rules. Here's what Uber Eats and DoorDash say they reward, and a checklist to get your listing ranking.",
    blocks: [
      { type: "p", text: "Uber Eats, DoorDash and SkipTheDishes work a lot like search engines. When a customer opens the app, the platform decides which restaurants to show first, which to feature in carousels and which to push down the list. Two restaurants serving the same food a block apart can see very different order volumes because of how their listings perform." },
      { type: "p", text: "The platforms don't publish their full ranking formulas. But Uber Eats and DoorDash do publish the performance programs they use to reward stores, and those tell you a lot about what they value." },
      { type: "h2", text: "What Uber Eats measures" },
      { type: "p", text: "Uber Eats gives stores a monthly **success score** that places each one in a tier from Excellent to Poor. According to Uber, it's based on operational excellence, menu markup, menu details, ratings and, where applicable, sustainable packaging ([Uber Eats](https://merchants.ubereats.com/gb/en/success-score))." },
      { type: "p", text: "Higher tiers unlock benefits such as placement in special carousels in the app and eligibility for programs like Top Eats. Stores in the Poor tier lose access to those benefits, and Uber says stores that stay there for several months may risk removal from the marketplace. Program details vary by market, so check what's shown in your own Uber Eats Manager." },
      { type: "h2", text: "What DoorDash measures" },
      { type: "p", text: "DoorDash's **Most Loved** program looks at four signals: missing and incorrect items, cancellations, photo coverage (the share of menu items with photos) and menu markup compared with your in-store prices ([DoorDash](https://merchants.doordash.com/en-us/learning-center/optimize-my-business)). DoorDash says Most Loved stores can get more homepage visibility, a dedicated carousel and a badge customers can see." },
      { type: "p", text: "Notice the overlap. Both platforms reward the same things: accurate orders, few cancellations, complete menus with photos, fair pricing and good ratings. SkipTheDishes doesn't publish an equivalent program, but those same fundamentals are what customers on any app respond to." },
      { type: "h2", text: "The ranking checklist" },
      { type: "h3", text: "1. Get your operations right first" },
      { type: "ul", items: [
        "**Keep hours accurate on every app**, including holidays. Orders placed while you're closed turn into cancellations.",
        "**Mark sold-out items immediately.** Out-of-stock items that stay listed are a common cause of cancellations and missing items.",
        "**Double-check bags before handoff.** Missing and incorrect items are tracked directly by DoorDash and drag down ratings everywhere.",
        "**Set realistic prep times** so orders are ready when the courier arrives.",
      ] },
      { type: "h3", text: "2. Build a menu that sells" },
      { type: "ul", items: [
        "**Put best sellers and signature dishes first.** Most customers never scroll past the first few categories.",
        "**Add a photo to every item you can**, starting with your top sellers. DoorDash explicitly measures photo coverage.",
        "**Write short, specific descriptions:** main ingredients, portion size and spice level.",
        "**Use modifiers and combos** to make add-ons easy, which raises average order value.",
      ] },
      { type: "h3", text: "3. Price fairly" },
      { type: "p", text: "Both Uber Eats and DoorDash factor in menu markup, meaning how far your app prices sit above your in-store prices. Many restaurants mark up delivery prices to offset commission, but a large markup can cost you visibility. Find the balance that protects your margin without hurting your standing in the app." },
      { type: "h3", text: "4. Protect your ratings" },
      { type: "ul", items: [
        "**Package food so it travels well.** Soggy fries and spilled curry hurt ratings more than slow delivery does.",
        "**Respond to issues quickly in your merchant portal** and dispute order problems that weren't your fault.",
        "**Watch for patterns.** If several reviews mention the same dish arriving cold, fix the dish or the packaging.",
      ] },
      { type: "h3", text: "5. Use promotions with a goal" },
      { type: "p", text: "Promotions and sponsored listings can lift visibility quickly, but they eat into margin. Run them with a clear goal, like new customers, bigger orders or filling quiet hours, and measure whether each one pays back. Turn off what doesn't." },
      { type: "h2", text: "Don't rely on the apps alone" },
      { type: "p", text: "Delivery apps are great for reaching new customers, but every order costs you commission. The restaurants that do best use the apps for discovery and give their regulars a reason to order directly, through ordering on their own website." },
      { type: "p", text: "If you're on Clover, we can build [commission-free online ordering on your own website](/services/clover-online-ordering) that prints straight to your kitchen, and manage your [Uber Eats, DoorDash and SkipTheDishes listings](/services/delivery-platforms) alongside it." },
    ],
    faqs: [
      { q: "Does marking up my prices on delivery apps hurt my ranking?", a: "It can. Both Uber Eats and DoorDash factor menu markup, compared with your in-store prices, into their store performance programs." },
      { q: "How often do Uber Eats and DoorDash update store performance scores?", a: "Both programs update monthly, based on the previous month's performance." },
      { q: "Do photos really matter on delivery apps?", a: "Yes. DoorDash measures photo coverage directly, and photos help customers choose. Start with your best-selling items." },
      { q: "Is SkipTheDishes different?", a: "SkipTheDishes doesn't publish a performance program like Uber Eats or DoorDash, but the same fundamentals apply: accurate orders, few cancellations, complete menus with photos, fair prices and good ratings." },
    ],
    sources: [
      { label: "Uber Eats: Introducing the success score", url: "https://merchants.ubereats.com/gb/en/success-score" },
      { label: "DoorDash: Road to Most Loved", url: "https://merchants.doordash.com/en-us/learning-center/optimize-my-business" },
    ],
  },
];

export const getPost = (slug) => posts.find((p) => p.slug === slug);
