// Blog / guides. Each post: blocks are rendered by components/PostBody.js.
// Inline syntax inside text: **bold** and [link text](url). Keep every claim sourced.

export const posts = [
  {
    slug: "how-to-get-more-google-reviews",
    title: "How to get more Google reviews (without breaking Google's rules)",
    seoTitle: "How to Get More Google Reviews Without Breaking the Rules",
    description:
      "A practical guide for Vancouver businesses: how to ask for Google reviews, what Google and Canadian law prohibit, and how to reply so reviews help you rank.",
    date: "2026-10-08",
    category: "Google Business Profile",
    service: "google-business-profile",
    readMinutes: 6,
    excerpt:
      "Reviews help you rank and help customers choose you. Here's how to get more of them the right way, and the shortcuts that can get your profile restricted.",
    blocks: [
      { type: "p", text: "For most local businesses, Google reviews do two jobs at once. They help customers decide between you and the place down the street, and they're one of the signals Google uses to decide who shows up in the map pack in the first place." },
      { type: "p", text: "Google says local results are based mainly on relevance, distance and prominence, and that \"more reviews and positive ratings can help your business's local ranking\" ([Google](https://support.google.com/business/answer/7091)). You can't change your distance from a searcher. You can change how many recent, genuine reviews you have." },
      { type: "h2", text: "Why the number and freshness of reviews matter" },
      { type: "p", text: "Customers read recent reviews to judge what a business is like now, not three years ago. A profile with a steady stream of new reviews, and thoughtful replies to them, looks active and trustworthy. A profile whose last review is from last spring looks like it might be closed." },
      { type: "p", text: "Volume matters too. A 4.8 from 12 reviews is less convincing than a 4.6 from 240. The goal isn't a perfect score. It's a steady flow of honest feedback from real customers." },
      { type: "h2", text: "What Google doesn't allow" },
      { type: "p", text: "Before you start asking, know where the lines are. Google's contributed content policy prohibits ([Google](https://support.google.com/contributionpolicy/answer/7400114)):" },
      { type: "ul", items: [
        "**Paying for reviews** or offering incentives such as discounts, free items or services in exchange for a review.",
        "**Selectively asking happy customers only** (often called review gating), or discouraging negative reviews.",
        "**Pressuring customers to review while they're still on the premises.**",
        "**Asking staff to collect reviews that include specific content**, such as particular keywords or phrases.",
        "**Reviews from people with a conflict of interest**, including current or former employees and contractors.",
      ] },
      { type: "p", text: "Google's own help page for businesses is blunt about incentives: offering free or discounted goods or services in exchange for reviews is \"strictly prohibited\" ([Google](https://support.google.com/business/answer/3474122)). Breaking these rules can get reviews removed and, in more serious cases, restrictions placed on your profile." },
      { type: "h2", text: "The Canadian side: fake reviews are a legal risk too" },
      { type: "p", text: "In Canada, the Competition Bureau treats fake reviews as misleading to consumers. It warns that companies posting fake reviews to boost their own ratings or hurt competitors \"are misleading consumers and harming businesses that play by the rules\" ([Competition Bureau](https://www.canada.ca/en/competition-bureau/news/2017/03/fake_online_reviewstoogoodtobetrue.html))." },
      { type: "p", text: "This isn't theoretical. In 2015, Bell Canada agreed to pay a $1.25 million penalty after employees were encouraged to post positive reviews of its apps without disclosing who they worked for ([iPhone in Canada](https://www.iphoneincanada.ca/2015/10/14/bell-fined-fake-reviews/))." },
      { type: "h2", text: "Seven ways to get more genuine reviews" },
      { type: "ol", items: [
        "**Make leaving a review effortless.** Get your review link or QR code from your Google Business Profile, as Google recommends ([Google](https://support.google.com/business/answer/3474122)). Every extra tap loses people.",
        "**Ask everyone, at the right moment.** Ask every customer, not just the ones who seem happy. Time it to when the value is fresh: after a meal, when a project is handed over, after a treatment or at the end of a program.",
        "**Put the QR code where customers already pause.** Table tents, the receipt, the counter, the checkout screen, the packaging. Let people scan it on their own time rather than pressing them on the spot.",
        "**Follow up by text or email.** A short message a few hours or a day later, with the direct link, consistently brings in more reviews than an in-person ask alone.",
        "**Train your team on the ask, not the wording.** Staff can say \"we'd really appreciate a Google review\", but they shouldn't tell customers what to write.",
        "**Reply to reviews, good and bad.** Customers notice when a business responds, and replies show Google the profile is actively managed.",
        "**Keep it steady.** Ten reviews in a week followed by nothing for months looks less natural, and helps you less, than two or three a week every week.",
      ] },
      { type: "h2", text: "How to reply to reviews" },
      { type: "p", text: "Google recommends that replies be polite, short and relevant, that you skip generic thank-yous, and that you don't use replies to advertise deals ([Google](https://support.google.com/business/answer/3474122)). In practice:" },
      { type: "ul", items: [
        "**Positive reviews:** thank them by name, mention something specific they said, and invite them back.",
        "**Negative reviews:** stay calm, acknowledge what went wrong, explain what you're doing about it and offer a way to continue the conversation privately. Never share a customer's private details or argue in public.",
        "**Reviews that break Google's rules:** flag them for removal through your Business Profile instead of arguing with the reviewer.",
      ] },
      { type: "tip", text: "Regulated professions such as physicians, nurses and dentists often have advertising rules about how patient reviews and testimonials can be used. You can usually still reply to reviews, but check your college's standards before featuring reviews in your marketing." },
      { type: "h2", text: "A simple review system you can set up this week" },
      { type: "ol", items: [
        "Copy your review link from your Google Business Profile and create a QR code.",
        "Add the QR code to your receipts, counter, table tents or invoices.",
        "Write a short follow-up text or email and send it to every customer within a day.",
        "Pick one person to reply to every new review within 48 hours.",
        "Check your review count once a month, and adjust where and when you ask.",
      ] },
      { type: "p", text: "If you'd rather have it done for you, we set up review systems as part of our [Google Business Profile management](/services/google-business-profile), including QR codes, follow-up messages and replies written in your brand voice." },
    ],
    faqs: [
      { q: "Can I offer a discount for a Google review?", a: "No. Google prohibits offering discounts, free items or any other incentive in exchange for reviews, and incentivized reviews can be removed." },
      { q: "Is it OK to only ask happy customers for reviews?", a: "No. Google's policy prohibits selectively asking for positive reviews. Ask every customer and let them share their honest experience." },
      { q: "Can my employees or family leave reviews?", a: "They shouldn't. Google's policy treats current and former employees and other conflicts of interest as fake engagement." },
      { q: "How many Google reviews do I need?", a: "There's no magic number. What matters most is having more recent, genuine reviews than the businesses you compete with in the map pack, and a steady flow of new ones." },
    ],
    sources: [
      { label: "Google: Tips to improve your local ranking", url: "https://support.google.com/business/answer/7091" },
      { label: "Google: Maps user contributed content policy (fake engagement)", url: "https://support.google.com/contributionpolicy/answer/7400114" },
      { label: "Google: Read & reply to reviews", url: "https://support.google.com/business/answer/3474122" },
      { label: "Competition Bureau Canada: Fake online reviews", url: "https://www.canada.ca/en/competition-bureau/news/2017/03/fake_online_reviewstoogoodtobetrue.html" },
      { label: "iPhone in Canada: Bell fined $1.25 million over fake app reviews", url: "https://www.iphoneincanada.ca/2015/10/14/bell-fined-fake-reviews/" },
    ],
  },
  {
    slug: "how-to-rank-higher-on-uber-eats-doordash-skipthedishes",
    title: "How to rank higher on Uber Eats, DoorDash and SkipTheDishes",
    seoTitle: "How to Rank Higher on Uber Eats, DoorDash & SkipTheDishes",
    description:
      "What the delivery apps actually reward, from ratings and photos to cancellations and menu markup, and a checklist BC restaurants can use to get more orders.",
    date: "2026-10-08",
    category: "Delivery platforms",
    service: "delivery-platforms",
    readMinutes: 5,
    excerpt:
      "Delivery apps are search engines with their own rules. Here's what Uber Eats and DoorDash say they reward, and a checklist to get your listing ranking.",
    blocks: [
      { type: "p", text: "Uber Eats, DoorDash and SkipTheDishes work a lot like search engines. When a customer opens the app, the platform decides which restaurants to show first, which to feature in carousels and which to push down the list. Two restaurants serving the same food a block apart can see very different order volumes because of how their listings perform." },
      { type: "p", text: "The platforms don't publish their full ranking formulas. But Uber Eats and DoorDash do publish the performance programs they use to reward stores, and those tell you a lot about what they value." },
      { type: "h2", text: "What Uber Eats measures" },
      { type: "p", text: "Uber Eats gives stores a monthly **success score** that places each one in a tier from Excellent to Poor. According to Uber, it's based on operational excellence, menu markup, menu details, ratings and, where applicable, sustainable packaging ([Uber Eats](https://merchants.ubereats.com/gb/en/success-score))." },
      { type: "p", text: "Higher tiers unlock benefits such as placement in special carousels in the app and eligibility for programs like Top Eats. Stores in the Poor tier lose access to those benefits, and Uber says stores that stay there for several months may risk removal from the marketplace. Program details vary by market, so check what's shown in your own Uber Eats Manager." },
      { type: "h2", text: "What DoorDash measures" },
      { type: "p", text: "DoorDash's **Most Loved** program looks at four signals: missing and incorrect items, cancellations, photo coverage (the share of menu items with photos) and menu markup compared with your in-store prices ([DoorDash](https://merchants.doordash.com/en-us/learning-center/optimize-my-business)). DoorDash says Most Loved stores can get more homepage visibility, a dedicated carousel and a badge customers can see." },
      { type: "p", text: "Notice the overlap. Both platforms reward the same things: accurate orders, few cancellations, complete menus with photos, fair pricing and good ratings. SkipTheDishes doesn't publish an equivalent program, but those same fundamentals are what customers on any app respond to." },
      { type: "h2", text: "The ranking checklist" },
      { type: "h3", text: "1. Get your operations right first" },
      { type: "ul", items: [
        "**Keep hours accurate on every app**, including holidays. Orders placed while you're closed turn into cancellations.",
        "**Mark sold-out items immediately.** Out-of-stock items that stay listed are a common cause of cancellations and missing items.",
        "**Double-check bags before handoff.** Missing and incorrect items are tracked directly by DoorDash and drag down ratings everywhere.",
        "**Set realistic prep times** so orders are ready when the courier arrives.",
      ] },
      { type: "h3", text: "2. Build a menu that sells" },
      { type: "ul", items: [
        "**Put best sellers and signature dishes first.** Most customers never scroll past the first few categories.",
        "**Add a photo to every item you can**, starting with your top sellers. DoorDash explicitly measures photo coverage.",
        "**Write short, specific descriptions:** main ingredients, portion size and spice level.",
        "**Use modifiers and combos** to make add-ons easy, which raises average order value.",
      ] },
      { type: "h3", text: "3. Price fairly" },
      { type: "p", text: "Both Uber Eats and DoorDash factor in menu markup, meaning how far your app prices sit above your in-store prices. Many restaurants mark up delivery prices to offset commission, but a large markup can cost you visibility. Find the balance that protects your margin without hurting your standing in the app." },
      { type: "h3", text: "4. Protect your ratings" },
      { type: "ul", items: [
        "**Package food so it travels well.** Soggy fries and spilled curry hurt ratings more than slow delivery does.",
        "**Respond to issues quickly in your merchant portal** and dispute order problems that weren't your fault.",
        "**Watch for patterns.** If several reviews mention the same dish arriving cold, fix the dish or the packaging.",
      ] },
      { type: "h3", text: "5. Use promotions with a goal" },
      { type: "p", text: "Promotions and sponsored listings can lift visibility quickly, but they eat into margin. Run them with a clear goal, like new customers, bigger orders or filling quiet hours, and measure whether each one pays back. Turn off what doesn't." },
      { type: "h2", text: "Don't rely on the apps alone" },
      { type: "p", text: "Delivery apps are great for reaching new customers, but every order costs you commission. The restaurants that do best use the apps for discovery and give their regulars a reason to order directly, through ordering on their own website." },
      { type: "p", text: "If you're on Clover, we can build [commission-free online ordering on your own website](/services/clover-online-ordering) that prints straight to your kitchen, and manage your [Uber Eats, DoorDash and SkipTheDishes listings](/services/delivery-platforms) alongside it." },
    ],
    faqs: [
      { q: "Does marking up my prices on delivery apps hurt my ranking?", a: "It can. Both Uber Eats and DoorDash factor menu markup, compared with your in-store prices, into their store performance programs." },
      { q: "How often do Uber Eats and DoorDash update store performance scores?", a: "Both programs update monthly, based on the previous month's performance." },
      { q: "Do photos really matter on delivery apps?", a: "Yes. DoorDash measures photo coverage directly, and photos help customers choose. Start with your best-selling items." },
      { q: "Is SkipTheDishes different?", a: "SkipTheDishes doesn't publish a performance program like Uber Eats or DoorDash, but the same fundamentals apply: accurate orders, few cancellations, complete menus with photos, fair prices and good ratings." },
    ],
    sources: [
      { label: "Uber Eats: Introducing the success score", url: "https://merchants.ubereats.com/gb/en/success-score" },
      { label: "DoorDash: Road to Most Loved", url: "https://merchants.doordash.com/en-us/learning-center/optimize-my-business" },
    ],
  },
  {
    slug: "google-maps-ranking-for-restaurants",
    title: "How to rank your restaurant higher on Google Maps",
    seoTitle: "How to Rank Your Restaurant Higher on Google Maps",
    description:
      "A step-by-step guide for BC restaurants: how Google ranks the map pack, and the profile, menu, photo, review and website fixes that move you up.",
    date: "2026-10-08",
    category: "Google Business Profile",
    service: "google-business-profile",
    readMinutes: 6,
    excerpt:
      "Most diners pick a restaurant from the map pack. Here's how Google decides who shows up, and what you can change this week to climb it.",
    blocks: [
      { type: "p", text: "When someone searches \"sushi near me\" or \"best butter chicken Surrey\", Google shows a map with a handful of restaurants. That map pack is where most diners decide where to eat, often without ever visiting a website. If you're not in it, you're mostly invisible for that search." },
      { type: "h2", text: "How Google decides who shows up" },
      { type: "p", text: "Google says local results are based mainly on three things ([Google](https://support.google.com/business/answer/7091)):" },
      { type: "ul", items: [
        "**Relevance:** how well your profile matches what someone searched for.",
        "**Distance:** how far you are from the searcher, or from the area they searched.",
        "**Prominence:** how well-known you are, including how many reviews you have, your ratings and how many websites link to you.",
      ] },
      { type: "p", text: "You can't move your restaurant closer to every customer. But relevance and prominence are largely in your control, and that's where every fix below comes in." },
      { type: "h2", text: "1. Get your profile basics exactly right" },
      { type: "ul", items: [
        "**Use your real name.** Google's guidelines say your business name should match your real-world name, and that adding unnecessary information to it isn't permitted ([Google](https://support.google.com/business/answer/3038177)). \"Raj's Kitchen\" is fine. \"Raj's Kitchen Best Indian Food Surrey Halal\" risks a suspension.",
        "**Choose your primary category carefully.** Pick the most specific category that describes what your restaurant is, such as \"Indian restaurant\" rather than just \"Restaurant\". Google advises using as few categories as possible and not using them as keywords ([Google](https://support.google.com/business/answer/3038177)).",
        "**Keep hours accurate, including holidays.** Wrong hours lead to bad experiences and bad reviews.",
        "**Fill in every attribute that applies:** dine-in, takeout, delivery, patio, vegetarian options, wheelchair access, reservations and so on. Attributes help you match more specific searches.",
      ] },
      { type: "h2", text: "2. Put your menu on Google" },
      { type: "p", text: "Food and drink businesses can add a menu directly to their Business Profile with Google's menu editor, upload menu photos or a PDF, and add a menu link ([Google](https://support.google.com/business/answer/9455840)). A complete menu helps Google match you to searches for specific dishes, not just your cuisine." },
      { type: "ul", items: [
        "Add your signature dishes with clear names and short descriptions.",
        "Upload clear menu photos as a backup, and remove outdated ones.",
        "Check what Google has pulled from your website. Google may transcribe menu data from your site, and you can edit or remove incorrect items ([Google](https://support.google.com/business/answer/9455840)).",
      ] },
      { type: "tip", text: "Menu changes can take 24 to 48 hours to appear on Google Maps and Search, so update holiday or seasonal menus a couple of days early." },
      { type: "h2", text: "3. Post photos every week" },
      { type: "p", text: "Photos are often the first thing diners look at. Upload real photos of your dishes, your dining room, your patio and your exterior so people recognize you from the street. Aim for a few new photos every week rather than a big batch once a year. Recent photos show the restaurant is active and help diners know what to expect." },
      { type: "h2", text: "4. Build a steady stream of reviews" },
      { type: "p", text: "Reviews feed directly into prominence: Google says \"more reviews and positive ratings can help your business's local ranking\" ([Google](https://support.google.com/business/answer/7091)). Ask every guest, make it easy with a QR code on the table or the receipt, and reply to every review. Never offer a discount or a free dessert in exchange. Our guide on [how to get more Google reviews](/blog/how-to-get-more-google-reviews) covers exactly how to do it within Google's rules." },
      { type: "h2", text: "5. Make it easy to order and book" },
      { type: "p", text: "Add your reservation and online ordering links to your profile. If you take orders on your own website, link to that first. It keeps the customer, and the margin, with you instead of a delivery app. Restaurants on Clover can do this with [commission-free online ordering](/services/clover-online-ordering) that prints straight to the kitchen." },
      { type: "h2", text: "6. Back it up with your website" },
      { type: "p", text: "Your Google profile and your website work together. Make sure your website shows the same name, address and phone number as your profile, loads fast on a phone, has your menu as real text (not just a PDF), and clearly says what neighbourhood you're in. Mentions and links from local food blogs, news sites and community pages also add to your prominence." },
      { type: "h2", text: "7. Keep the profile active" },
      { type: "ul", items: [
        "Publish a Google Post every week: a new dish, a special, an event or a holiday menu.",
        "Check your profile regularly for edits suggested by Google or the public, and correct anything wrong.",
        "Watch your ranking for your top two or three searches each month to see whether the changes are working.",
      ] },
      { type: "h2", text: "A quick checklist" },
      { type: "ol", items: [
        "Business name matches your sign, with no extra keywords.",
        "The most specific primary category, plus a few relevant secondary ones.",
        "Hours, holiday hours and attributes complete and accurate.",
        "Full menu on Google, with no outdated items.",
        "New photos every week.",
        "A review QR code at every table or on every receipt, and a reply to every review.",
        "Reservation and ordering links added.",
        "Website matches your profile and loads fast on mobile.",
      ] },
      { type: "p", text: "Want us to run it for you? Our [Google Business Profile management](/services/google-business-profile) covers all of this every week for restaurants across Metro Vancouver and Vancouver Island." },
    ],
    faqs: [
      { q: "Can I add keywords to my Google business name to rank higher?", a: "No. Google's guidelines require your real-world business name, and adding extra information can lead to your profile being suspended." },
      { q: "How long does it take to rank higher on Google Maps?", a: "Fixes like categories, menu and attributes can help within weeks. Building enough reviews and activity to beat competitors in a busy area usually takes a few months of steady work." },
      { q: "Do Google Posts help my ranking?", a: "Posts keep your profile current and give customers a reason to choose you. Treat them as part of keeping the profile active rather than a ranking shortcut." },
      { q: "Why does my restaurant show up for some searches but not others?", a: "Relevance and distance change with every search. A complete profile with the right categories, menu and attributes helps you match more searches, and reviews and links help you compete further from your location." },
    ],
    sources: [
      { label: "Google: Tips to improve your local ranking", url: "https://support.google.com/business/answer/7091" },
      { label: "Google: Guidelines for representing your business", url: "https://support.google.com/business/answer/3038177" },
      { label: "Google: Add or edit your menu", url: "https://support.google.com/business/answer/9455840" },
    ],
  },
  {
    slug: "what-happened-to-google-business-profile-qa",
    title: "What happened to Google Business Profile Q&A, and what to do now",
    seoTitle: "What Happened to Google Business Profile Q&A? What to Do",
    description:
      "Google replaced Business Profile Q&A with an AI \"Ask\" feature in Maps. Here's what changed, what powers the answers now and how to keep them accurate.",
    date: "2026-10-08",
    category: "Google Business Profile",
    service: "google-business-profile",
    readMinutes: 4,
    excerpt:
      "The Questions & Answers section is gone from Maps. Customers now get AI answers built from your profile and reviews. Here's how to make sure they're right.",
    blocks: [
      { type: "p", text: "For years, Google Business Profiles had a public Questions & Answers section where anyone could ask a question and anyone, including the business, could answer it. That section is being replaced. Customers now ask their question in Google Maps and get an AI-generated answer instead of scrolling through old questions." },
      { type: "h2", text: "What changed, and when" },
      { type: "ul", items: [
        "**September 17, 2025:** Google announced that the Q&A API (which tools and agencies used to manage questions) would be discontinued.",
        "**November 3, 2025:** the Q&A API was shut down.",
        "**December 3, 2025:** Google confirmed that Q&A is being replaced by an \"Ask\" feature in Maps.",
      ] },
      { type: "p", text: "Google said customers will be able to ask a question and get \"an updated, instant answer based on your answers and relevant reviews\", and explained that it had become harder for customers to wade through all the questions as the feature grew ([PPC Land](https://ppc.land/google-quietly-kills-q-a-for-an-ai-button-most-wont-use/))." },
      { type: "h2", text: "Where the AI answers come from" },
      { type: "p", text: "According to Google's announcement, the answers draw on information the business has provided and on relevant reviews ([PPC Land](https://ppc.land/google-quietly-kills-q-a-for-an-ai-button-most-wont-use/)). In practice, that means two things matter more than ever:" },
      { type: "ul", items: [
        "**Your profile details:** hours, services, menu or products, attributes and your description.",
        "**What your customers say in reviews**, and how you reply to them.",
      ] },
      { type: "p", text: "If your profile says you have a patio but three recent reviews complain there isn't one, you can't control which answer a customer gets. Accurate details and consistent reviews give the AI less to get wrong." },
      { type: "h2", text: "What to do now" },
      { type: "ol", items: [
        "**Complete every field you can.** Services, products or menu, attributes like parking, accessibility, payment options and booking, and an accurate description.",
        "**Answer the questions customers ask most, in your profile and on your website.** Parking, reservations, dietary options, prices, wait times, insurance, booking policies: put clear answers where Google can read them. An FAQ section on your website helps here too.",
        "**Reply to reviews with useful details.** A reply like \"Yes, we have free parking behind the building\" adds accurate information, not just a thank-you.",
        "**Keep hours and holiday hours current.** \"Are you open?\" is the question customers ask most.",
        "**Check what Maps says about you.** Search for your business in Maps every month and try the questions your customers would ask. If an answer is wrong, fix the source: your profile, your website or the issue customers keep raising in reviews.",
        "**Answer customer questions when Google surfaces them.** Google said businesses can still respond to aggregated customer questions, which helps answer others asking something similar ([PPC Land](https://ppc.land/google-quietly-kills-q-a-for-an-ai-button-most-wont-use/)).",
      ] },
      { type: "tip", text: "Google is rolling this change out gradually, so what you see on your own profile may differ from these dates for a while. The fundamentals above help either way." },
      { type: "h2", text: "The bottom line" },
      { type: "p", text: "You no longer get to write the answer to each question directly. Instead, the quality of your profile and your reviews decides what customers hear. That rewards businesses that keep their profile complete and current, which is exactly what we focus on in our [Google Business Profile management](/services/google-business-profile)." },
    ],
    faqs: [
      { q: "Is Google Business Profile Q&A gone?", a: "Google is replacing the public Q&A section with an AI \"Ask\" feature in Maps that answers customer questions using business-provided information and relevant reviews." },
      { q: "Can I still answer customer questions?", a: "Google said businesses can respond to aggregated customer questions. The bigger lever now is keeping your profile, website and review replies complete and accurate." },
      { q: "What happens to my old questions and answers?", a: "Google hasn't said how long historical Q&A content will be kept. Make sure the important answers also live in your profile details and on your website." },
      { q: "How do I stop the AI from giving wrong answers about my business?", a: "Fix the source. Keep your hours, services and attributes accurate, answer common questions on your website, and address recurring issues customers mention in reviews." },
    ],
    sources: [
      { label: "PPC Land: Google replaces Q&A with an AI Ask button", url: "https://ppc.land/google-quietly-kills-q-a-for-an-ai-button-most-wont-use/" },
      { label: "Google: Tips to improve your local ranking", url: "https://support.google.com/business/answer/7091" },
    ],
  },
  {
    slug: "how-much-does-seo-cost-in-canada",
    title: "How much does SEO cost in Canada?",
    seoTitle: "How Much Does SEO Cost in Canada? A Plain-English Guide",
    description:
      "Typical SEO price ranges in Canada for local and small businesses, what drives the cost, how pricing models work and the red flags to avoid.",
    date: "2026-10-08",
    category: "Local SEO",
    service: "seo",
    readMinutes: 6,
    excerpt:
      "SEO pricing is all over the map. Here are the typical ranges Canadian businesses see, what changes the price and how to tell a fair quote from a bad deal.",
    blocks: [
      { type: "p", text: "Ask five agencies what SEO costs and you'll get five very different answers. That's partly because \"SEO\" covers everything from fixing a few page titles to running a national content and link-building program. This guide explains the typical ranges, what pushes the price up or down and how to judge a quote." },
      { type: "tip", text: "The figures below are market ranges from published industry sources, not our pricing. Every business is different, and the only reliable number is a quote based on an audit of your own site and market." },
      { type: "h2", text: "Typical SEO price ranges" },
      { type: "p", text: "There's no large, rigorous survey of Canadian SEO prices. The best available data comes from two kinds of sources: agency-published rate cards and international surveys of SEO providers." },
      { type: "h3", text: "Advertised Canadian rates (CAD)" },
      { type: "p", text: "Based on published Canadian agency rate cards as of 2026 ([Wise Media](https://wisemedia.io/2026/08/25/how-much-does-seo-cost-in-canada/)):" },
      { type: "ul", items: [
        "**Local SEO retainers:** roughly $1,000 to $3,000 a month.",
        "**Small business growth retainers:** roughly $1,500 to $5,000 a month.",
        "**Competitive or national campaigns:** roughly $3,000 to $10,000+ a month.",
        "**Hourly consulting:** roughly $100 to $250 an hour.",
        "**One-time technical audits:** roughly $1,500 to $5,000.",
      ] },
      { type: "p", text: "The same source is clear that these are advertised rates, not survey data, so treat them as a guide rather than a rule." },
      { type: "h3", text: "Survey data from SEO providers (USD)" },
      { type: "p", text: "An Ahrefs survey of 439 SEO providers found that the most common monthly retainer worldwide was $501 to $1,000 USD. Providers in the U.S. and Canada charged more: 79.1% charged at least $1,001 USD a month, and two-thirds charged between $75 and $200 USD an hour ([Ahrefs](https://ahrefs.com/blog/seo-pricing))." },
      { type: "h2", text: "What changes the price" },
      { type: "ul", items: [
        "**How competitive your searches are.** Ranking for \"dentist Vancouver\" takes far more work than ranking for a niche service in a smaller town.",
        "**How many locations or cities you target.** Each location usually needs its own Google Business Profile work and its own pages.",
        "**The state of your website.** A slow, outdated or poorly structured site needs fixing before content and links pay off.",
        "**How much content is needed.** Service pages, location pages and guides take time to research and write well.",
        "**Whether links and citations are included.** Earning quality local links and directory listings is ongoing work.",
        "**What else is bundled in.** Google Business Profile management, reporting and conversion tracking may or may not be part of the price.",
      ] },
      { type: "h2", text: "How SEO is usually priced" },
      { type: "ul", items: [
        "**Monthly retainer:** the most common model for ongoing SEO. You pay a set amount each month for an agreed scope of work.",
        "**One-time project:** an audit, a site migration or a fixed set of fixes, priced up front.",
        "**Hourly consulting:** useful if you have an in-house team and need expert guidance rather than hands-on work.",
      ] },
      { type: "p", text: "For most local businesses, a monthly retainer makes sense because local SEO isn't a one-time fix. Rankings depend on steady work: new content, new reviews, updated listings and ongoing technical upkeep." },
      { type: "h2", text: "Red flags to watch for" },
      { type: "ul", items: [
        "**Guaranteed first-page rankings.** No one controls Google's results. A guarantee usually means vague keywords nobody searches for, or risky tactics.",
        "**Very cheap packages with no clear deliverables.** If you can't see what's being done each month, you can't tell if it's working.",
        "**Buying links or reviews.** Paid reviews break Google's rules, and low-quality link schemes can hurt your rankings.",
        "**Long lock-in contracts with no reporting.** You should get regular, plain-language reports on what was done and what changed.",
        "**You don't own your accounts.** Your website, Google Business Profile, Search Console and Analytics should be in your business's name.",
      ] },
      { type: "h2", text: "Questions to ask before you hire anyone" },
      { type: "ol", items: [
        "What exactly will you do each month, and how will I see it?",
        "Which searches will you target, and why those?",
        "How will you measure results: rankings, traffic, calls or leads?",
        "Who owns the accounts and content you create?",
        "What's the minimum term, and what happens if I want to stop?",
        "Can you show me results for a business like mine?",
      ] },
      { type: "h2", text: "Is SEO worth it for a local business?" },
      { type: "p", text: "It depends on what a new customer is worth to you. For a café, one extra customer might be worth $15. For a dental implant practice, a renovation company or a sports academy, one new customer can be worth thousands. The higher the value of a customer, the faster a few extra leads a month cover the cost of SEO." },
      { type: "p", text: "The honest answer is that SEO is a medium-term investment. Expect a few months before rankings and leads move meaningfully in a competitive market. If you need customers next week, pair SEO with [Google Ads](/services/google-meta-ads) while it builds." },
      { type: "p", text: "Want to know what SEO would involve for your business? We start every engagement with a free audit of your site, your Google Business Profile and your competitors, so you can see the gaps before you commit. Learn more about our [local SEO services](/services/seo)." },
    ],
    faqs: [
      { q: "How much does local SEO cost per month in Canada?", a: "Published Canadian agency rate cards put local SEO retainers at roughly $1,000 to $3,000 CAD a month. The right price for your business depends on your market, your website and how many locations you target." },
      { q: "Why do SEO quotes vary so much?", a: "Because the scope varies. Some packages cover a few technical fixes, while others include content, Google Business Profile management, link building and reporting. Compare what's delivered each month, not just the price." },
      { q: "Can I do SEO myself?", a: "You can handle the basics yourself: an accurate Google Business Profile, steady reviews, clear service pages and a fast site. Competitive markets usually need more time and expertise than most owners have to spare." },
      { q: "How long before SEO pays off?", a: "Technical fixes and Google Business Profile improvements can help within weeks. In competitive markets, expect three to six months of consistent work before rankings and leads move meaningfully." },
    ],
    sources: [
      { label: "Wise Media: How much does SEO cost in Canada? (2026)", url: "https://wisemedia.io/2026/08/25/how-much-does-seo-cost-in-canada/" },
      { label: "Ahrefs: SEO pricing survey", url: "https://ahrefs.com/blog/seo-pricing" },
    ],
  },
  {
    slug: "google-business-profile-not-showing-up",
    title: "Why isn't my Google Business Profile showing up?",
    seoTitle: "Google Business Profile Not Showing Up? 9 Reasons & Fixes",
    description:
      "The most common reasons a Google Business Profile doesn't appear in Search or Maps, from verification and suspensions to categories and competition, with fixes.",
    date: "2026-10-08",
    category: "Google Business Profile",
    service: "google-business-profile",
    readMinutes: 6,
    excerpt:
      "Your profile is set up but customers can't find it. Here are the most common causes, how to tell which one you have and what to do about each.",
    blocks: [
      { type: "p", text: "Few things are more frustrating than searching for your own business and not finding it. Usually the cause is one of a handful of issues, and most of them can be fixed. Work through these in order." },
      { type: "h2", text: "First, check how you're searching" },
      { type: "p", text: "Search for your exact business name on Google Maps. If your profile appears for your name but not for searches like \"florist near me\", your profile exists and is visible; the issue is ranking, not visibility. Jump to reasons 6 to 9. If it doesn't appear even for your exact name, start with reasons 1 to 5." },
      { type: "h2", text: "1. Your profile isn't verified" },
      { type: "p", text: "You need to verify your business to edit your information on Google and interact with customers ([Google](https://support.google.com/business/answer/7107242))." },
      { type: "p", text: "**Fix:** complete verification from your Business Profile. Google chooses the method automatically, which may be phone or text, email, video or a postcard. Reviews can take up to five business days, and postcards usually arrive within 14 days ([Google](https://support.google.com/business/answer/7107242))." },
      { type: "h2", text: "2. Your profile is suspended" },
      { type: "p", text: "Google may suspend or disable profiles that don't follow its guidelines ([Google](https://support.google.com/business/answer/4569145)). Common triggers include keywords in the business name, using a virtual office or mailbox as an address, or listing a service-area business at an address customers can't visit." },
      { type: "p", text: "**Fix:** correct whatever breaks the guidelines, then submit an appeal through Google's appeals tool with evidence such as a business licence, registration or utility bill showing your name and address. Don't create a new profile for the same business while an appeal is pending ([Google](https://support.google.com/business/answer/4569145))." },
      { type: "h2", text: "3. It's a brand-new profile or was recently edited" },
      { type: "p", text: "New profiles and major edits, such as a new name, address or category, can take time to appear and may go under review. Avoid making lots of big changes at once, which can trigger extra review." },
      { type: "h2", text: "4. There's a duplicate listing" },
      { type: "p", text: "If an old or duplicate listing exists for the same business, Google may show that one instead of yours, or split your reviews between them. This is common after a move or a rebrand." },
      { type: "p", text: "**Fix:** search Maps for your name, address and phone number. If you find a duplicate, request ownership or report it as a duplicate so it can be merged or removed." },
      { type: "h2", text: "5. Your address or service area is set up wrong" },
      { type: "p", text: "Google requires a precise, accurate address or service area, and businesses that rent a mailing address without operating there aren't eligible for a profile ([Google](https://support.google.com/business/answer/3038177)). Service-area businesses should hide their address and set the areas they serve." },
      { type: "h2", text: "6. Your category doesn't match the search" },
      { type: "p", text: "Relevance is one of the main ranking factors ([Google](https://support.google.com/business/answer/7091)). If your primary category is \"Store\" and someone searches \"florist\", you'll struggle to show up. Choose the most specific category that describes your business, and add a few relevant secondary categories." },
      { type: "h2", text: "7. The searcher is too far away" },
      { type: "p", text: "Distance matters ([Google](https://support.google.com/business/answer/7091)). You'll almost always rank better for searches near your location than across the city. Don't fake addresses to get around this. Instead, build prominence with reviews, local content and links so you can compete further out." },
      { type: "h2", text: "8. Your profile is incomplete or inactive" },
      { type: "p", text: "Profiles with missing hours, services, photos or descriptions give Google less to match against. Fill in every relevant field, add photos regularly and post updates so the profile stays active." },
      { type: "h2", text: "9. Your competitors are simply stronger" },
      { type: "p", text: "Prominence includes how many reviews you have, your ratings and how many websites link to you ([Google](https://support.google.com/business/answer/7091)). If competitors have hundreds of recent reviews and you have a dozen, they'll usually outrank you. The fix is steady work: more genuine reviews, regular replies and a website that supports your profile. See our guide on [how to get more Google reviews](/blog/how-to-get-more-google-reviews)." },
      { type: "h2", text: "Quick diagnosis" },
      { type: "ul", items: [
        "**Not visible even for your exact name:** check verification, suspension, duplicates and your address.",
        "**Visible for your name, not for services:** check categories, completeness and reviews.",
        "**Visible nearby, not across town:** that's distance. Build reviews, content and links.",
        "**Was ranking, then dropped:** check for recent edits, a suspension notice, a new competitor or a wave of edits suggested by others.",
      ] },
      { type: "p", text: "If you've worked through this list and still can't find the problem, we'll take a look. Our free audit checks your [Google Business Profile](/services/google-business-profile), your rankings and your competitors, and shows exactly what's holding you back." },
    ],
    faqs: [
      { q: "Why can I find my business on Google but customers can't?", a: "Google personalizes results by location and search history. Search from a different device or in a private window, and try the searches your customers use, not just your business name." },
      { q: "How long does it take for a new Google Business Profile to show up?", a: "It varies. After verification, many profiles appear within days, but new profiles and major edits can be reviewed first. Verification reviews can take up to five business days." },
      { q: "Will creating a new profile fix a suspended one?", a: "No. Google advises against creating a new profile for the same business while an appeal is pending. Fix the issue and appeal instead." },
      { q: "Can adding keywords to my business name help me show up?", a: "It might help briefly, but it breaks Google's guidelines and is a common reason profiles get suspended. Use your real business name and put keywords in your categories, services and description." },
    ],
    sources: [
      { label: "Google: Verify your business on Google", url: "https://support.google.com/business/answer/7107242" },
      { label: "Google: Business Profile suspensions and appeals", url: "https://support.google.com/business/answer/4569145" },
      { label: "Google: Guidelines for representing your business", url: "https://support.google.com/business/answer/3038177" },
      { label: "Google: Tips to improve your local ranking", url: "https://support.google.com/business/answer/7091" },
    ],
  },
];

export const getPost = (slug) => posts.find((p) => p.slug === slug);
